CREATE TABLE gogame
(
ID int NOT NULL AUTO_INCREMENT,
CREATIONTIME varchar(255) NOT NULL,
PRIMARY KEY (ID)
)

CREATE TABLE clickitem
(
ID int NOT NULL AUTO_INCREMENT,
CREATIONTIME varchar(255) NOT NULL,
ROW int NOT NULL,
COL int NOT NULL,
GOGAME_ID int NOT NULL,
PRIMARY KEY (ID)
)

